# Generated by Django 4.1.6 on 2023-02-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('repo_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('second_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='TODO_2.project')),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('active', models.BooleanField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TODO_2.users')),
            ],
        ),
    ]
