# Generated by Django 4.1.6 on 2023-02-24 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TODO_2.users'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
