# Generated by Django 4.1.6 on 2023-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_2', '0002_todo_update_alter_todo_active_alter_todo_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
