# Generated by Django 4.1.6 on 2023-03-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_2', '0003_alter_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
